### ISSUE TITLE
Prepare terraform to spawn 1 vm on libvirt

### ISSUE THREAD

**Issue by torgiren** [DevOps-Together/torgiren-bot-infra#5]
Create tf file to create one VM on libvirt (if needed, we provide access to PLUG's libvirt) with
- 2 CPUs
- 4GB of memory

Use cloudinit for initial configuration (users, hostnames, ip addresses, etc)

Acceptance criteria
- tf file should use libvirt provider to spawn one domain
-VM should have 2 CPUs, 4 GB of memory
- use host-passthrough cpu model
- enable qemu-agent
- use hostname cotaining username
- create an initial user for future user provisioning
- consider setting static ip address (terraform vs ansible) (static address is needed for port forwarding)
- if needed, use tfvars (tf file should be general and reusable for multiple environments and libvirt hosts)
- prepare README file with instructions how to use proposed solution

other parameters are up to user to make the solution optimal

**Comment by goodbit22** [comment]
jest wymagany konkretny system czy moze być centos8 ?

**Comment by camaeel** [comment]
Centos jest to nie jest juz donry wybor na cokolwiek co ma byc bezpieczne, wspierane, aktualizowane itd.
https://linuxpolska.pl/aktualnosci/koniec-wsparcia-dla-centos/

**Comment by goodbit22** [comment]
CentOS Stream masz wsparcie jesli chodzi o security do 2024

**Comment by camaeel** [comment]
Stream jest ok do takiego projektu edukacyjnego.

**Comment by goodbit22** [comment]
rozwiązane
