### ISSUE TITLE
upgrade rke 1.18 to newer version

### ISSUE THREAD

**Issue by torgiren** [DevOps-Together/torgiren-bot-infra#9]
1.18 is quite old.
we can upgrade to 1.25 or change refactor it to a variable (default as 1.25)

**Comment by camaeel** [comment]
If you installed already 1.18 then the upgrades should be done 1 minor version at a time. 
If the cluster is empty I would recommend to wipe it out and do a fresh install with 1.25.

**Comment by torgiren** [comment]
we don't have a cluster right now.
and that ticket is to change the ansible code to configure yum.repos and install task
